spring:
    profiles:
        active: '@profile.active@'
        include: '@env.PRODUCT@,default'

    data:
        mongodb:
            uri: 'mongodb://192.168.1.189:32000/dfs_tm'
            cursorBatchSize: 1000
springdoc:
    enabled: true
tcm:
    url: http://192.168.1.189:30103
