env:
  server: "127.0.0.1:3000"
  access_token: "3324cfdf-7d3e-4792-bd32-571638d4562f"

qa_mongodb:
  connector: "mongodb"
  uri: "mongodb://root:Gotapd8!@139.198.127.204:32550/qa?authSource=admin"
  __core: true
  __cdc_source: true
  __type: ["source", "sink", "cdc"]

qa_mysql:
  connector: "mysql"
  host: "139.198.127.204"
  port: 31066
  username: "root"
  password: "Gotapd8!"
  database: "qa"
  __core: true
  __type: ["source", "sink", "cdc"]

