name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: tapdata-docker.pkg.coding.net/tapdata/tldp/build:0.1

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker images
